name: TryTheGrid
favicon: null
layout_spectrum: 0.20668
typography_spectrum: 0.88933
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ef7d22'
    - '#4170c7'
    - '#000000'
    - '#ff0000'
  brandStrength: 0.75
  lightness: 0.8125
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
