name: TryTheGrid
favicon: null
layout_spectrum: 0.923275574343279
typography_spectrum: 0.88933
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#981821'
    - '#af702d'
    - '#fdfff2'
    - '#ff9f4b'
    - '#6a82b4'
  brandStrength: 0.3125
  lightness: 0.8125
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
