name: TryTheGrid
favicon: null
layout_spectrum: 0.923275574343279
typography_spectrum: 0.05226477491669357
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#981821'
    - '#af702d'
    - '#fdfff2'
    - '#ff9f4b'
    - '#6a82b4'
  brandStrength: 0.22912875935435295
  lightness: 0.833546076901257
  saturation: 0.37447053426876664
  rhythmicContrast: 0.848577553872019
purpose: []
